project_id = "oquyabvzplwgdiqxctft"

[functions.health]
verify_jwt = false

[functions.swap-cash-in]
verify_jwt = false

[functions.swap-cash-out]
verify_jwt = false

[functions.wallet-transfer]
verify_jwt = false

[functions.lending-post-offer]
verify_jwt = false

[functions.lending-take-offer]
verify_jwt = false

[functions.lending-repayment]
verify_jwt = false

[functions.mysql-admin-login]
verify_jwt = false

[functions.mysql-admin-session]
verify_jwt = false

[functions.mysql-task-proofs]
verify_jwt = false

[functions.mysql-approve-proof]
verify_jwt = false

[functions.mysql-user-data]
verify_jwt = false

[functions.daily-vault-yield]
verify_jwt = false

[functions.auto-loan-repayment]
verify_jwt = false

[functions.get-payment-methods]
verify_jwt = false
