project_id = "oquyabvzplwgdiqxctft"

[functions.swap-cash-in]
verify_jwt = true

[functions.swap-cash-out]
verify_jwt = true

[functions.wallet-transfer]
verify_jwt = true

[functions.lending-post-offer]
verify_jwt = true

[functions.lending-take-offer]
verify_jwt = true

[functions.lending-repayment]
verify_jwt = true
